package com.apache.catalina;


/**
 * Interface defining a listener for significant events (including "component start"
 * and "component stop" generated by a component that implements the
 * Lifecycle interface. The listener will be fired after the associated state
 * change has taken place
 *
 * Created by xjk on 3/9/17.
 */
public interface LifecycleListener {

    /**
     * Acknowledge the occurrence of the specified event
     * @param event
     */
    void lifecycleEvent(LifecycleEvent event);

}
